apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-frontend
  template:
    metadata:
      labels:
        app: angular-frontend
    spec:
      containers:
      - name: frontend
        image: farahbenchikha/angular-frontend:v1 # image frontend Angular
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: angular-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081 # Accessible depuis Windows sur http://192.168.233.190:30081
